### ISSUE TITLE
New Docs?

### ISSUE THREAD

**Issue by Hkr32** [hestiacp/hestiacp-docs#38]
I thought of translating the documentation into Russian and spent a lot of time deploying the current version to Netlify. 
Thought it might be better to use a modern documentation tool? My documentation suggestion: https://hestiacpdocs.netlify.app/
I'm not an expert, but it seems to me that it will be more convenient and easier to write documentation, markdown is simpler.
My Source: https://github.com/w3ref/hestiacp-docs-vuepress

**Comment by jaapmarcus** [comment]
I do agree the markdown is slightly easier. Also the output for https://github.com/hestiacp/hestia-cli-docs was by default mark-down (Converted to RST) For current Hestia-docs..

**Comment by jaapmarcus** [comment]
We have more demand from more users  to translate  parts of the docs.. 

https://www.sphinx-doc.org/en/master/usage/advanced/intl.html

Supports Multi language support for Sphinx doc

Other option might be Vuepress

**Comment by Hkr32** [comment]
I've been through a lot already. I think that as I transfer the rest, I'll try to make a translation)

**Comment by jaapmarcus** [comment]
Just wait for the moment. We want to prevent 10 different "Hestia" docs sites getting created with often "outdated" information.. It is easier to keep everything in one location... 

Please join Discord if you can. Url is in Hestia main repo...  Makes communication easier...

**Comment by imjuniper** [comment]
The docs are currently being rebuilt with VitePress over on the [develop branch](/hestiacp/hestiacp-docs/tree/develop)! The preview is available on https://dev.hestiacp.com.

**Comment by imjuniper** [comment]
I will actually leave this open as the tracking issue.

**Comment by imjuniper** [comment]
Closing, since the new docs have been merged in the main repo and also they will be released really soon.
