### ISSUE TITLE
Document default web templates

### ISSUE THREAD

**Issue by xeruf** [hestiacp/hestiacp-docs#51]
https://docs.hestiacp.com/admin_docs/web.html#how-do-web-templates-work
- When to use the default nginx templates default/caching/hosting?
- The selected Web template seems to be ignored when a domain redirect is enabled, then it uses `proxy_ip`. This should be improved in the UI but until then documented.
  -> so maybe https://github.com/hestiacp/hestiacp/issues/1453 can be implemented by offering form fields based on the template?

**Comment by jaapmarcus** [comment]
This repository has been replace by https://github.com/hestiacp/hestiacp/tree/main/docs
Please submit any changes to https://github.com/hestiacp/hestiacp directly

default = default
caching = mostly static content for example a wordpress site with a lot of traffic
hosting = is default should removed

Redirect is enabled it should still use the template that is selected but it is loaded first and should ignore the rest
