### ISSUE TITLE
Architect overview

### ISSUE THREAD

**Issue by jaapmarcus** [hestiacp/hestiacp-docs#8]
See:
https://github.com/hestiacp/hestiacp/issues/1515

**Comment by imjuniper** [comment]
@ScIT-Raphael @jaapmarcus When you guys have time, could you give me an overview of what everything does and how everything interacts together? I'll create a page for this in the new docs. Also maybe reasons to choose some options (e.g. enabling Sieve or not, using Vsftpd vs ProFTPD, Multi-PHP, etc.)?

**Comment by jaapmarcus** [comment]
Idea is to keep it decently light weight as not all users but most "settings" are taken over from "VestaCP"

MultiPHP could be removed currently adding extra php versions is nothing more that run:
v-add-web-php x.x where x.x is the version
