### ISSUE TITLE
CLI Commands Rework

### ISSUE THREAD

**Issue by jlguerrerosanz** [hestiacp/hestiacp-docs#9]
I think that the CLI documentation requires a complete rework

For example:
```
v-generate-password-hash
generate password hash

Label: panel

Options: HASH_METHOD SALT PASSWORD

Examples:

v-generate-password-hash sha-512 rAnDom_string yourPassWord
The function generates password hash
```
HASH_METHOD: Which hash methods are available? 
- sha1 or sha-1 or SHA1 or SHA-1
- sha2
- md5 or MD5
- ...

SALT: how long should that string be?

What happens if there is an error. How does it treat exit codes?

### Enhancement:
```
v-generate-password-hash
The function echoes password hash

Return 0. Ok
Return 1. Error

Label: panel

Options: HASH_METHOD SALT PASSWORD
- HASH_METHOD:
 - md5
 - sha-1
 - sha-2
- SALT: text string up to 128 chars

Examples:
v-generate-password-hash sha-512 rAnDom_string yourPassWord

v-generate-password-hash md5 rAnDom_string yourPassWord

```

I know it is a lot of work but I am willing to help with that.

**Comment by jaapmarcus** [comment]
Return codes are already recorded under 
https://docs.hestiacp.com/admin_docs/rest_api.html#return-codes

If I check the CLI lists from VestaCP it is more close to the "old" Hestia list.

I would personally focus first on the other "issues" ("https://github.com/hestiacp/hestiacp-docs/issues)  for improving the docs.  And focus  on questions that get happened a lot on Forum/Githhub.  It still could use an "proof read" as English isn't the main language for a lot of us.

**Comment by jaapmarcus** [comment]
Changes have allready been made how ever never got closed... Will close the issue
